services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: "postgres://user:password@host:port/dbname"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
